title:        Notebook
tagline:      "PDFields Notebook"
url:          http://peterdfields.github.io/
author:
  name:       ""
  email:      ""
markdown:     kramdown   
permalink:    pretty
highlighter:  rouge
paginate:     5
