title:        Notebook
tagline:      "PDFields Notebook"
url:          http://peterdfields.github.io/
author:
  name:       ""
  email:      ""
markdown:     
permalink:    pretty
pygments:     true
paginate:     5
highlighter:   rouge
